version: '3'

services:
  db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
  server:
    build: ./server/
    working_dir: /var/www/server
    env_file:
      - .env
    command: python manage.py runserver $SERVER_HOST:$SERVER_PORT
    volumes:
      - ./server/:/var/www/server
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - db